services:
  - type: web
    name: ai-research-knowledge-assistant
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    autoDeploy: false

    envVars:
      - key: APP_ENV
        value: production

      - key: DEBUG
        value: "false"

      - key: DATABASE_URL
        value: sqlite:////app/data/app.db

      - key: UPLOAD_DIR
        value: /app/data/raw_documents

      - key: VECTOR_DB_DIR
        value: /app/data/vector_db

      - key: IMAGES_DIR
        value: /app/data/extracted_images

      - key: MODEL_PATH
        value: /app/models/document_classifier.keras

      - key: VECTORIZER_PATH
        value: /app/models/text_vectorizer.pkl

      - key: LABEL_ENCODER_PATH
        value: /app/models/label_encoder.pkl

      - key: GEMINI_API_KEY
        sync: false

      - key: JWT_SECRET_KEY
        generateValue: true

      - key: JWT_ALGORITHM
        value: HS256

      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

      - key: OCR_ENABLED
        value: "true"

      - key: CACHE_BACKEND
        value: memory

      - key: STREAMING_ENABLED
        value: "true"